[package]
name = "summand_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive"] }
summand_data = { path = "../summand_data" }

[lib]
name = "summand_cli"
path = "src/lib.rs"
