[package]
name = "summand_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.140"
summand_app = { path = "../summand_app" }

[lib]
name = "summand_parser"
path = "src/lib.rs"
