name: "First Interaction Lable"
on: [issues, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Code-Hex/first-label-interaction@v1.0.2
        with:
          issue-labels: '["first"]'
          pr-labels: '["first"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
